openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipes app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the documentation for the Recipes app.
tags:
  - name: Recipes
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Ingredients
    description: Operations to manage ingredients.

servers:
  - url: https://response-201-back.onrender.com
    description: development server
paths:
  /api/recipes:
    get:
      $ref: ../swagger/paths/api/recipes/get.yaml
    post:
      $ref: ../swagger/paths/api/recipes/post.yaml

  /api/recipes/myRecipes:
    get:
      $ref: ../swagger/paths/api/recipes/myRecipes/get.yaml

  /api/recipes/favorites:
    patch:
      $ref: ../swagger/paths/api/recipes/{id}/favorites/get.yaml

  /api/recipes/{recipeId}:
    delete:
      $ref: ../swagger/paths/api/recipes/myRecipes/delete.yaml
    get:
      $ref: ../swagger/paths/api/recipes/{id}/get.yaml

  /api/recipes/{recipeId}/favorites:
    patch:
      $ref: ../swagger/paths/api/recipes/{id}/favorites/patch.yaml
    delete:
      $ref: ../swagger/paths/api/recipes/{id}/favorites/delete.yaml

  /api/ingredients:
    get:
      $ref: ../swagger/paths/api/ingredients/get.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/api/auth/login/post.yaml

  /api/auth/register:
    post:
      $ref: ../swagger/paths/api/auth/register/post.yaml

  /api/auth/logout:
    post:
      $ref: ../swagger/paths/api/auth/logout/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
