type: object
required:
  - nameRecipe
  - instructions
  - ingredients
  - recipeCategory
  - cookingTime
  - recipeDescription
  - owner
properties:
  nameRecipe:
    type: string
    example: "Cabbage Soup"
  dishPhoto:
    type: string
    format: url
    example: "http://example.com/photo.jpg"
  recipeDescription:
    type: string
    example: "A classic British cake made with almond sponge cake..."
  instructions:
    type: string
    example: "Preheat oven to 350° F. Spray a 9x13-inch baking pan..."
  ingredients:
    type: array
    items:
      type: object
      required:
        - id
        - measure
      properties:
        id:
          type: string
          example: "6462a8f74c3d0ddd28897fbf"
        measure:
          type: string
          example: "200g"
  recipeCategory:
    type: string
    example: "Lamb"
  cookingTime:
    type: string
    example: "30"
  owner:
    type: string
    example: "5f8f8c44c9e77a001a1b2c3d"
