type: object
required:
  - nameRecipe
  - recipeDescription
  - ingredients
  - recipeCategory
  - calories
  - cookingTime
  - owner
properties:
  nameRecipe:
    type: string
    example: "Cabbage Soup"
  dishPhoto:
    type: string
    format: url
    example: "http://example.com/photo.jpg"
  recipeDescription:
    type: array
    items:
      type: string
    example:
      - "Chop cabbage"
      - "Boil water"
      - "Cook for 30 minutes"
  ingredients:
    type: array
    items:
      type: object
      required:
        - name
        - measure
      properties:
        name:
          type: string
          example: "Cabbage"
        measure:
          type: string
          example: "200g"
  recipeCategory:
    type: string
    example: "Lamb"
  calories:
    type: number
    example: 250
  cookingTime:
    type: number
    example: 30
  owner:
    type: string
    example: "5f8f8c44c9e77a001a1b2c3d"
